---
- name: Set password expiration, warning, and account disable periods
  user:
    name: "{{ item }}"
    password_expire_min: "{{ password_expiration_data.expire_min }}"
    password_expire_max: "{{ password_expiration_data.expire_max }}"
    password_expire_warn: "{{ password_expiration_data.expire_warn }}"
    password_expire_account_disable: "{{ password_expiration_data.expire_account_disable }}"
  loop: "{{ regular_users }}"
  when:
    - password_expiration == true
    - item is not in ignore_users

- name: Prevent guest users from changing their password
  user:
    name: "{{ item }}"
    password_expire_min: 99999 # users can not change their passwords if min days
    password_expire_max: 99998 # between password change is greater than password expiry
  loop: "{{ guest_users }}"