---
- name: Install package for PAM password quality
  apt:
    name: "{{ PAM_pwquality_package }}"

- name: Back up the configuration file on the managed node
  copy:
    src: "{{ PAM_pwquality_filepath }}"       # "/etc/pam.d/common-password"
    dest: "{{ PAM_pwquality_filepath }}.back" # "/etc/pam.d/common-password.back"
    remote_src: yes
  
- name: Enforce password quality rules
  lineinfile:
    path: "{{ PAM_pwquality_filepath }}"      # "/etc/pam.d/common-password"
    regexp: "^password.*pam_pwquality.so"
    line: "password requisite pam_pwquality.so retry=10 difok=6 minlen={{ password_complexity.min_length }} ucredit=-1 lcredit=-1 dcredit=-1 ocredit=-1 [badwords=root toor admin 123123] enforce_for_root"
    insertafter: "^password.*pam_unix.so"
    state: present
    