---
#- name: Ensure PAM package is installed
#  package:
#    name: pam
#    state: present

- name: Ensure faillock configuration directory exists
  file:
    path: "{{ password_lockout.lockout_directory }}"
    state: directory
    mode: '0755'
    
- name: Back up the faillock configuration file on managed nodes
  copy:
    src: "/etc/security/faillock.conf"
    dest: "/etc/security/faillock.conf.back"
    remote_src: true

- name: Generate faillock.conf from a template
  template:
    src: faillock.conf.j2
    dest: /etc/security/faillock.conf
    owner: root
    group: root
    mode: "0644"

- name: Ensure PAM uses the faillock module to enforce the rules
  lineinfile:
    path: "{{ password_lockout.PAM_config }}"
    regexp: "^auth required pam_faillock.so"
    line: "auth required pam_faillock.so preauth"
    insertbefore: "^-auth.*pam_systemd_home.so"
    state: "present"

- name: Ensure the PAM faillock configuration for authentication is in place
  lineinfile:
    path: "{{ password_lockout.PAM_config }}"
    line: "auth required pam_faillock.so authfail"
    insertafter: "^auth.*pam_unix.so"
    state: present

- name: Ensure the PAM faillock configuration for account is in place
  lineinfile:
    path: "{{ password_lockout.PAM_config }}"
    line: "account required pam_faillock.so"
    insertafter: "^account.*pam_unix.so"
    state: present